ch17ex01: ch17ex01.o ../lib/my_functions.o
	gcc -o ../bin/ch17ex01 ch17ex01.o ../lib/my_functions.o

ch17ex01.o: ch17ex01.c ../lib/my_functions.h
	gcc -c ch17ex01.c

my_functions.o: ../lib/my_functions.c ../lib/my_functions.h
	gcc -c ../lib/my_functions.c



